### PR TITLE
switch to ava

### PR DESCRIPTION
**Pull request by OmgImAlexis**
This will allow us to maintain this easier as it reduces the test file's length by about 2/3 and uses ava like the other projects in agenda's org.

### CODE REVIEW

**Comment by simison** [comment]
Awesome!

LGTM :thumbsup:

I [just added](https://github.com/agenda/human-interval/commit/4f5ef00be1c03a6c5b22bb04e82160f25769b385) Travis config to `master` so that we can run tests in Travis as well. 

~https://travis-ci.org/agenda (I don't have access to add this there, ping @joeframbach @niftylettuce)~
Edit: actually I do have rights, I was just confused by Travis interface. I'll add this there.

**Comment by simison** [comment]
Next up we could add a ton more tests to cover all the situations _we think_ this package _should_ cover (although it'll probably [fail on some](https://github.com/agenda/agenda/issues/540#issuecomment-337550763)).

**Comment by OmgImAlexis** [comment]
Did you mean to close this?

**Comment by simison** [comment]
Nah, my bad! wrote at slack more.
 

-- 
www.mikaelkorpela.fi

**Pull request closed without merging**
